"use client";

import React, { useState, useEffect, useRef } from "react";
import { 
  ChevronLeft, ChevronRight, Play, Download, LayoutGrid, X, 
  Loader2, Presentation, ArrowLeft, RefreshCw, FileText, Check, 
  MessageSquare, Edit3, Save, Maximize2, ShieldAlert, Sparkles, Image as ImageIcon
} from "lucide-react";
import Link from "next/link";
import api from "@/config/api";
import { cn } from "@/lib/utils";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { PPT_THEMES_MAP } from "@/config/ppt-themes";

interface Slide {
  id: number;
  title: string;
  subtitle?: string;
  layout: 
    | "title" | "section_break" | "conclusion"
    | "bullets" | "paragraph" | "quote" | "two_column_text"
    | "comparison" | "pros_cons" | "metric_callout" | "matrix_2x2"
    | "timeline" | "steps" | "roadmap"
    | "image_left" | "image_right" | "gallery_grid"
    | "metric";
  bullets?: string[];
  columns?: { left: string[]; right: string[] };
  metric?: { value: string; label: string; description: string };
  speakerNotes: string;
  variantIndex?: number;
  bgImageIndex?: number;
  
  // Custom layout fields
  author?: string;
  content?: string;
  quote_text?: string;
  role?: string;
  left_text?: string;
  right_text?: string;
  pros?: string[];
  cons?: string[];
  metrics?: { value: string; label: string }[];
  quadrants?: string[];
  events?: { year: string; description: string }[];
  steps?: string[];
  phases?: { phase: string; goal: string }[];
  image_url?: string;
  alt_text?: string;
  images?: string[];
}

interface PresentationData {
  _id?: string;
  title: string;
  slides: Slide[];
  theme?: string;
}

export default function AIPPTViewer({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = React.use(params);
  const [loading, setLoading] = useState(true);
  const [presentation, setPresentation] = useState<PresentationData | null>(null);
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);
  const [activeRightTab, setActiveRightTab] = useState<"notes" | "outline" | "design">("notes");
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isExporting, setIsExporting] = useState<"pptx" | "pdf" | null>(null);

  const containerRef = useRef<HTMLDivElement>(null);
  const slideNotesRef = useRef<HTMLTextAreaElement>(null);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(1);

  // Load presentation from API or generate mock content if slug not found
  useEffect(() => {
    const fetchPresentation = async () => {
      setLoading(true);
      try {
        const token = localStorage.getItem("authToken");
        // Try requesting from api
        const res = await api.get(`/presentation/${slug}`, {
          headers: { 'Auth': token }
        });
        if (res.data?.success && res.data?.presentation) {
          setPresentation(res.data.presentation);
        } else {
          throw new Error("No slide deck data found");
        }
      } catch (err) {
        console.warn("Backend presentation API not found, creating dynamic mock presentation for demo.");
        // Generate beautiful mock presentation based on slug title
        const niceTitle = slug
          .replace(/-/g, " ")
          .replace(/\b\w/g, (c) => c.toUpperCase());

        const mockSlides: Slide[] = [
          {
            id: 1,
            title: niceTitle,
            subtitle: "Generated by Paperxify AI Slide Builder",
            layout: "title",
            speakerNotes: "Welcome everyone to today's presentation. Today we will be exploring the core aspects of " + niceTitle + ". We'll cover fundamental principles, comparisons, and look at some key statistics."
          },
          {
            id: 2,
            title: "Core Objectives & Learning Outcomes",
            layout: "bullets",
            bullets: [
              "Understand the essential foundations and definitions.",
              "Analyze comparative structures and engineering trade-offs.",
              "Review practical industry metrics and deployments.",
              "Implement best practices for immediate scaling."
            ],
            speakerNotes: "Before diving deep, let's establish our objectives. We want to grasp the foundations, look at systems trade-offs, and then evaluate live metrics."
          },
          {
            id: 3,
            title: "System Architecture Comparison",
            layout: "comparison",
            columns: {
              left: [
                "Legacy Frameworks:",
                "Monolithic code blocks",
                "High latency overhead",
                "Strict schema constraints"
              ],
              right: [
                "AI-Powered Engines:",
                "Distributed vector nodes",
                "Sub-millisecond latency",
                "Dynamic contextual schema"
              ]
            },
            speakerNotes: "This slide compares legacy monolithic frameworks against modern AI-powered engines. Notice how latency scales down to sub-milliseconds while vector databases provide dynamic schemas."
          },
          {
            id: 4,
            title: "Key Performance Indicators",
            layout: "metric",
            metric: {
              value: "99.4%",
              label: "Recall Accuracy Rate",
              description: "Measured across 1.2M training sets under extreme token distribution conditions."
            },
            speakerNotes: "Here we have our key metric. We achieved a 99.4% accuracy rate, which represents a massive improvement over traditional transformers under dense recall scenarios."
          },
          {
            id: 5,
            title: "Future Roadmap & Summary",
            layout: "bullets",
            bullets: [
              "Phase 1: Scale distributed node clusters.",
              "Phase 2: Integrate real-time Whisper captioning.",
              "Phase 3: Deploy self-correcting prompt scripts."
            ],
            speakerNotes: "To wrap up, our roadmap contains three clear phases. First, we scale clusters. Next, we integrate speech-to-text. Finally, we implement self-correcting prompts."
          }
        ];

        setPresentation({
          title: niceTitle,
          slides: mockSlides
        });
      } finally {
        setLoading(false);
      }
    };

    fetchPresentation();
  }, [slug]);

  // Keyboard navigation for active slides and fullscreen modes
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!presentation) return;
      if (e.key === "ArrowRight" || e.key === "Space") {
        e.preventDefault();
        setActiveSlideIndex((prev) => Math.min(presentation.slides.length - 1, prev + 1));
      } else if (e.key === "ArrowLeft") {
        e.preventDefault();
        setActiveSlideIndex((prev) => Math.max(0, prev - 1));
      } else if (e.key === "Escape" && isFullscreen) {
        setIsFullscreen(false);
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [presentation, isFullscreen]);

  // Sync fullscreen state change
  useEffect(() => {
    const onFullscreenChange = () => {
      setIsFullscreen(!!document.fullscreenElement);
    };
    document.addEventListener("fullscreenchange", onFullscreenChange);
    return () => document.removeEventListener("fullscreenchange", onFullscreenChange);
  }, []);

  // Resize listener to scale slide preview proportionally
  useEffect(() => {
    if (isFullscreen) {
      setScale(1);
      return;
    }
    const handleResize = () => {
      if (!wrapperRef.current) return;
      const parentWidth = wrapperRef.current.clientWidth;
      const parentHeight = wrapperRef.current.clientHeight;
      // Scale to fit both width and height (16:9 canvas is 960x540)
      const scaleByWidth = parentWidth / 960;
      const scaleByHeight = parentHeight / 540;
      const newScale = Math.min(1, scaleByWidth, scaleByHeight);
      setScale(newScale);
    };

    window.addEventListener("resize", handleResize);
    handleResize();

    let resizeObserver: ResizeObserver | null = null;
    if (typeof ResizeObserver !== "undefined" && wrapperRef.current) {
      resizeObserver = new ResizeObserver(() => {
        handleResize();
      });
      resizeObserver.observe(wrapperRef.current);
    }

    return () => {
      window.removeEventListener("resize", handleResize);
      if (resizeObserver) {
        resizeObserver.disconnect();
      }
    };
  }, [isFullscreen]);

  const triggerFullscreen = () => {
    if (!containerRef.current) return;
    if (!isFullscreen) {
      containerRef.current.requestFullscreen().then(() => {
        setIsFullscreen(true);
      }).catch((err) => {
        toast.error("Failed to enter fullscreen mode.");
      });
    } else {
      document.exitFullscreen().then(() => {
        setIsFullscreen(false);
      });
    }
  };

  const handleExport = async (format: "pptx" | "pdf") => {
    setIsExporting(format);
    try {
      const token = localStorage.getItem("authToken");
      const res = await api.get(`/presentation/${slug}/export/${format}`, {
        headers: { 'Auth': token },
        responseType: 'blob'
      });
      
      const blob = new Blob([res.data], { 
        type: format === 'pdf' 
          ? 'application/pdf' 
          : 'application/vnd.openxmlformats-officedocument.presentationml.presentation' 
      });
      
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${slug}.${format}`);
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
      window.URL.revokeObjectURL(url);
      
      toast.success(`Presentation successfully exported as ${format.toUpperCase()}!`);
    } catch (err) {
      console.error(err);
      toast.error(`Failed to export presentation as ${format.toUpperCase()}`);
    } finally {
      setIsExporting(null);
    }
  };

  const updateNotes = (newVal: string) => {
    if (!presentation) return;
    const updatedSlides = [...presentation.slides];
    updatedSlides[activeSlideIndex].speakerNotes = newVal;
    setPresentation({
      ...presentation,
      slides: updatedSlides
    });
  };

  const changeTheme = (themeId: string) => {
    if (!presentation) return;
    setPresentation({
      ...presentation,
      theme: themeId
    });
    toast.success(`Theme switched to ${PPT_THEMES_MAP[themeId]?.name || themeId}`);
  };

  const changeSlideVariant = (index: number) => {
    if (!presentation) return;
    const updatedSlides = [...presentation.slides];
    updatedSlides[activeSlideIndex] = {
      ...updatedSlides[activeSlideIndex],
      variantIndex: index
    };
    setPresentation({
      ...presentation,
      slides: updatedSlides
    });
  };

  const changeSlideBackground = (index: number) => {
    if (!presentation) return;
    const updatedSlides = [...presentation.slides];
    updatedSlides[activeSlideIndex] = {
      ...updatedSlides[activeSlideIndex],
      bgImageIndex: index
    };
    setPresentation({
      ...presentation,
      slides: updatedSlides
    });
  };

  // Debounced auto-save effect
  useEffect(() => {
    if (!presentation || !presentation._id || presentation._id.startsWith('demo')) return;
    
    const delayDebounce = setTimeout(async () => {
      try {
        const token = localStorage.getItem("authToken");
        await api.put(`/presentation/update/${presentation._id}`, {
          slides: presentation.slides,
          theme: presentation.theme
        }, {
          headers: { 'Auth': token }
        });
      } catch (err) {
        console.error("Failed to auto-save slide updates:", err);
      }
    }, 1500);

    return () => clearTimeout(delayDebounce);
  }, [presentation]);

  if (loading) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center text-white">
        <Loader2 className="animate-spin text-orange-500 mb-4" size={40} />
        <p className="font-mono text-xs text-neutral-400 animate-pulse">Launching presentation slide environment...</p>
      </div>
    );
  }

  if (!presentation) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center text-white px-4 text-center">
        <ShieldAlert className="text-orange-500 mb-4" size={48} />
        <h2 className="text-xl font-bold mb-4">Presentation Not Found</h2>
        <Link href="/presentation-generator" className="px-5 py-2.5 bg-orange-500 text-black font-bold text-xs uppercase tracking-widest rounded-xl">
          Return to Dashboard
        </Link>
      </div>
    );
  }

  const slides = presentation.slides;
  const currentSlide = slides[activeSlideIndex];

  // Resolve dynamic theme and active layout variant
  const activeThemeId = presentation.theme || "sunset-orange";
  const activeTheme = PPT_THEMES_MAP[activeThemeId] || PPT_THEMES_MAP["sunset-orange"];
  const layoutsForType = (activeTheme.layouts[currentSlide.layout] || []) as any[];
  const variantIndex = currentSlide.variantIndex || 0;
  const activeVariantIndex = variantIndex < layoutsForType.length ? variantIndex : 0;
  const activeVariant = layoutsForType[activeVariantIndex];

  // Background image resolver
  const slideBgUrl = currentSlide.bgImageIndex && currentSlide.bgImageIndex > 0 && currentSlide.bgImageIndex <= activeTheme.bgImages.length
    ? activeTheme.bgImages[currentSlide.bgImageIndex - 1]
    : null;

  return (
    <div className="h-screen bg-[#070707] text-white flex flex-col font-sans select-none relative overflow-hidden pt-16">
      
      {/* HEADER CONTROL BAR */}
      <header className="fixed top-0 inset-x-0 h-16 bg-[#0a0a0a]/90 backdrop-blur-xl border-b border-white/[0.04] flex items-center justify-between px-4 lg:px-8 z-40 transform-gpu shadow-sm">
        <div className="flex items-center gap-4">
          <Link href="/presentation-generator" className="p-2 bg-neutral-900 border border-white/[0.08] hover:border-orange-500/30 rounded-lg text-neutral-400 hover:text-white transition-all">
            <ArrowLeft size={14} />
          </Link>
          <div>
            <span className="font-bold text-sm tracking-tight text-white block truncate max-w-[200px] sm:max-w-md">{presentation.title}</span>
            <span className="text-[9px] font-black uppercase tracking-widest text-orange-500/70 flex items-center gap-1">
              <Presentation size={9} /> PPT Workspace
            </span>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          {/* Present Slideshow */}
          <button 
            onClick={triggerFullscreen}
            className="flex items-center gap-1.5 h-10 px-4 rounded-xl text-[10px] font-bold uppercase tracking-widest text-black bg-gradient-to-r from-orange-500 to-amber-500 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all active:scale-95 shrink-0"
          >
            <Play size={11} fill="currentColor" /> Present
          </button>

          {/* Export Dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger className="flex items-center gap-1.5 h-10 px-3.5 rounded-xl bg-white/[0.04] border border-white/[0.07] hover:bg-white/[0.06] hover:border-white/15 text-[10px] font-bold uppercase tracking-wider text-neutral-300 hover:text-white transition-all duration-200 outline-none shrink-0">
              {isExporting ? <Loader2 size={12} className="animate-spin text-orange-500" /> : <Download size={12} />}
              <span>Export</span>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-[#0c0c0c] border border-white/[0.08] text-white p-1.5 rounded-xl shadow-2xl z-50">
              <DropdownMenuItem 
                onClick={() => handleExport("pptx")}
                className="flex items-center gap-2 text-xs font-semibold rounded-lg cursor-pointer px-3 py-2 hover:bg-white/5 focus:bg-white/5"
              >
                <Presentation size={12} className="text-orange-500" /> Export as PPTX
              </DropdownMenuItem>
              <DropdownMenuItem 
                onClick={() => handleExport("pdf")}
                className="flex items-center gap-2 text-xs font-semibold rounded-lg cursor-pointer px-3 py-2 hover:bg-white/5 focus:bg-white/5"
              >
                <FileText size={12} className="text-red-500" /> Export as PDF
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>

      {/* CORE WORKSPACE PANES */}
      <div className="flex-1 flex flex-col md:flex-row overflow-hidden h-[calc(100vh-64px)]">
        
        {/* LEFT PANEL: SLIDE THUMBNAILS (20%) */}
        <aside className="w-56 shrink-0 bg-[#090909] border-r border-white/[0.04] p-4 overflow-y-auto hidden md:flex flex-col gap-3 custom-scrollbar h-full">
          <p className="text-[8px] font-black uppercase tracking-[0.25em] text-neutral-500 mb-2">Slide Navigation</p>
          {slides.map((slide, idx) => {
            const isActive = activeSlideIndex === idx;
            return (
              <div
                key={slide.id}
                onClick={() => setActiveSlideIndex(idx)}
                className={cn(
                  "cursor-pointer flex flex-col gap-1.5 p-2.5 rounded-xl border transition-all text-left group",
                  isActive 
                    ? "bg-orange-500/10 border-orange-500/40 shadow-sm" 
                    : "bg-white/[0.01] border-white/[0.05] hover:border-white/15 hover:bg-white/[0.02]"
                )}
              >
                <div className="flex justify-between items-center text-[9px] font-mono text-neutral-500">
                  <span>Slide {idx + 1}</span>
                  {isActive && <span className="w-1.5 h-1.5 rounded-full bg-orange-500" />}
                </div>
                <span className={cn("text-[11px] font-bold truncate", isActive ? "text-orange-400" : "text-neutral-300 group-hover:text-white")}>
                  {slide.title || `Slide ${idx + 1}`}
                </span>
                
                {/* Visual outline mockup inside thumbnail */}
                <div className="w-full aspect-[16/9] rounded-lg bg-black border border-white/[0.04] mt-1 flex items-center justify-center">
                  <LayoutGrid size={12} className={cn(isActive ? "text-orange-500/40" : "text-white/10")} />
                </div>
              </div>
            );
          })}
        </aside>

        {/* CENTER PANEL: INTERACTIVE CANVAS AREA */}
        <main className="flex-1 bg-black p-4 lg:p-6 flex flex-col overflow-hidden h-full">
          
          {/* Active slide viewport (16:9 widescreen card) */}
          <div ref={wrapperRef} className="w-full flex-1 flex items-center justify-center relative overflow-hidden min-h-0">
            <div className="w-full aspect-[16/9] max-w-4xl relative overflow-hidden flex items-center justify-center">
              <div 
                ref={containerRef}
                className={cn(
                  "absolute rounded-2xl border relative overflow-hidden flex flex-col justify-between shadow-2xl transition-all duration-500",
                  isFullscreen 
                    ? "w-screen h-screen max-w-none rounded-none border-none bg-black p-12 sm:p-20" 
                    : `bg-gradient-to-br ${activeTheme.bgGradient} border-white/[0.08] p-8 sm:p-12`
                )}
                style={{
                  fontFamily: activeTheme.fontFamily,
                  width: isFullscreen ? "100%" : "960px",
                  height: isFullscreen ? "100%" : "540px",
                  transform: isFullscreen ? "none" : `translate(-50%, -50%) scale(${scale})`,
                  left: isFullscreen ? "0" : "50%",
                  top: isFullscreen ? "0" : "50%",
                  position: isFullscreen ? "fixed" : "absolute",
                  transformOrigin: "center center",
                  zIndex: isFullscreen ? 50 : 10
                }}
              >
                {/* Background image if selected */}
                {slideBgUrl && (
                  <>
                    <div 
                      className="absolute inset-0 bg-cover bg-center transition-all duration-500" 
                      style={{ backgroundImage: `url(${slideBgUrl})` }} 
                    />
                    {/* Contrast tint overlay */}
                    <div className="absolute inset-0 bg-black/75 backdrop-blur-[0.5px] transition-all" />
                  </>
                )}

                {/* Background ppt-like slide branding elements (only if no bg image to avoid clutter) */}
                {!slideBgUrl && (
                  <>
                    <div className="absolute top-0 right-0 w-[40%] h-[40%] bg-gradient-to-bl from-white/[0.01] to-transparent rounded-bl-full pointer-events-none" />
                    <div className="absolute bottom-0 left-0 w-[30%] h-[30%] bg-gradient-to-tr from-white/[0.01] to-transparent rounded-tr-full pointer-events-none" />
                  </>
                )}

                {/* Top Row: Slide layout label */}
                <div className="flex justify-between items-center text-[10px] font-mono text-neutral-500 z-10">
                  <span>{presentation.title}</span>
                  <span className="uppercase tracking-widest text-[9px] px-2 py-0.5 rounded border border-white/5 bg-black/45" style={{ color: activeTheme.colors.primary }}>
                    {currentSlide.layout.replace("_", " ")} Layout
                  </span>
                </div>

                {/* Main Content Area based on Layout */}
                <div className="my-auto flex-1 flex flex-col justify-center min-h-0 pt-4 z-10">
                  {activeVariant ? (
                    activeVariant.render(currentSlide, activeTheme.colors)
                  ) : (
                    <div className="text-center py-6">
                      <h2 className="text-xl font-bold">{currentSlide.title}</h2>
                      <p className="text-xs text-neutral-400">Layout "{currentSlide.layout}" is not configured for this theme.</p>
                    </div>
                  )}
                </div>

                {/* Bottom Row: Slide numbers & controls */}
                <div className="flex justify-between items-center text-[10px] font-mono text-neutral-500 pt-2 border-t border-white/[0.04] z-10">
                  <span>Paperxify AI Presentations</span>
                  <span>Slide {activeSlideIndex + 1} of {slides.length}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Onscreen Slide Switcher */}
          <div className="flex justify-center items-center gap-4 bg-white/[0.02] border border-white/[0.06] rounded-xl px-5 py-2.5 mx-auto max-w-xs shrink-0 mt-3">
            <button 
              onClick={() => setActiveSlideIndex((prev) => Math.max(0, prev - 1))}
              disabled={activeSlideIndex === 0}
              className="p-1.5 rounded-lg hover:bg-white/5 hover:text-white text-neutral-400 transition-colors disabled:opacity-20"
            >
              <ChevronLeft size={16} />
            </button>
            <span className="text-xs font-mono font-bold text-neutral-300 select-none">
              {activeSlideIndex + 1} / {slides.length}
            </span>
            <button 
              onClick={() => setActiveSlideIndex((prev) => Math.min(slides.length - 1, prev + 1))}
              disabled={activeSlideIndex === slides.length - 1}
              className="p-1.5 rounded-lg hover:bg-white/5 hover:text-white text-neutral-400 transition-colors disabled:opacity-20"
            >
              <ChevronRight size={16} />
            </button>
          </div>
        </main>

        {/* RIGHT PANEL: SPEAKER NOTES / OUTLINE / DESIGN (25%) */}
        <aside className="w-full md:w-80 shrink-0 bg-[#090909] border-t md:border-t-0 md:border-l border-white/[0.04] flex flex-col overflow-hidden h-[380px] md:h-full">
          
          {/* Workspace Tabs */}
          <div className="flex border-b border-white/[0.05] bg-[#0c0c0c] p-1.5 gap-1 shrink-0">
            <button 
              onClick={() => setActiveRightTab("notes")}
              className={cn(
                "flex-1 py-1.5 text-[11px] font-bold rounded-lg transition-all flex items-center justify-center gap-1.5",
                activeRightTab === "notes" ? "bg-orange-500/10 text-orange-400" : "text-neutral-500 hover:text-neutral-300"
              )}
            >
              <MessageSquare size={11} /> Notes
            </button>
            <button 
              onClick={() => setActiveRightTab("outline")}
              className={cn(
                "flex-1 py-1.5 text-[11px] font-bold rounded-lg transition-all flex items-center justify-center gap-1.5",
                activeRightTab === "outline" ? "bg-orange-500/10 text-orange-400" : "text-neutral-500 hover:text-neutral-300"
              )}
            >
              <LayoutGrid size={11} /> Outline
            </button>
            <button 
              onClick={() => setActiveRightTab("design")}
              className={cn(
                "flex-1 py-1.5 text-[11px] font-bold rounded-lg transition-all flex items-center justify-center gap-1.5",
                activeRightTab === "design" ? "bg-orange-500/10 text-orange-400" : "text-neutral-500 hover:text-neutral-300"
              )}
            >
              <Sparkles size={11} /> Design
            </button>
          </div>

          {/* Active Tab View */}
          <div className="flex-1 overflow-y-auto p-5 custom-scrollbar min-h-0 flex flex-col justify-between">
            <AnimatePresence mode="wait">
              {activeRightTab === "notes" && (
                <motion.div 
                  key="notes-tab"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-4 flex-1 flex flex-col h-full"
                >
                  <div className="flex justify-between items-center shrink-0">
                    <span className="text-[9px] font-black uppercase tracking-[0.2em] text-neutral-500">Active Speaker Script</span>
                    <span className="text-[10px] text-orange-500/60 font-medium flex items-center gap-1"><Edit3 size={10} /> Auto-Saving</span>
                  </div>
                  
                  {/* Speaker script textarea */}
                  <textarea
                    ref={slideNotesRef}
                    value={currentSlide.speakerNotes}
                    onChange={(e) => updateNotes(e.target.value)}
                    placeholder="Enter presenter speaker notes for this slide..."
                    className="flex-1 w-full bg-black/40 border border-white/5 hover:border-white/10 focus:border-orange-500/50 rounded-xl p-3.5 text-xs text-neutral-305 placeholder:text-neutral-600 focus:outline-none resize-none leading-relaxed min-h-[250px] outline-none transition-all font-light"
                  />
                  <div className="p-3 rounded-xl bg-orange-500/5 border border-orange-500/10 flex items-start gap-2.5 shrink-0">
                    <span className="text-xs shrink-0 mt-0.5">💡</span>
                    <p className="text-[10px] text-neutral-400 leading-normal font-light">
                      Presenter speaker notes are generated dynamically by AI based on slide topic context. Click and edit directly to customize.
                    </p>
                  </div>
                </motion.div>
              )}

              {activeRightTab === "outline" && (
                <motion.div 
                  key="outline-tab"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-4 text-left"
                >
                  <span className="text-[9px] font-black uppercase tracking-[0.2em] text-neutral-500 block font-bold">Deck Outline Map</span>
                  <div className="space-y-2.5 border-l border-white/10 ml-2 pl-3 py-1">
                    {slides.map((s, idx) => (
                      <div 
                        key={s.id} 
                        onClick={() => setActiveSlideIndex(idx)}
                        className={cn(
                          "cursor-pointer text-xs font-semibold py-1 hover:text-white transition-all text-left relative",
                          activeSlideIndex === idx ? "text-orange-455" : "text-neutral-400"
                        )}
                      >
                        {activeSlideIndex === idx && (
                          <div className="absolute left-[-16px] top-1/2 -translate-y-1/2 w-2 h-2 rounded-full bg-orange-500" />
                        )}
                        <span className="font-mono text-[10px] opacity-50 mr-1">0{idx + 1}.</span> {s.title}
                      </div>
                    ))}
                  </div>
                </motion.div>
              )}

              {activeRightTab === "design" && (
                <motion.div 
                  key="design-tab"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-6 flex-1 flex flex-col h-full text-left"
                >
                  {/* Presentation Themes Section */}
                  <div className="space-y-2.5">
                    <span className="text-[9px] font-black uppercase tracking-[0.2em] text-neutral-500 block">Select Presentation Theme</span>
                    <div className="grid grid-cols-1 gap-2">
                      {Object.values(PPT_THEMES_MAP).map((t) => {
                        const isSelected = activeTheme.id === t.id;
                        return (
                          <button
                            key={t.id}
                            type="button"
                            onClick={() => changeTheme(t.id)}
                            className={cn(
                              "w-full p-3 rounded-xl border text-left transition-all flex items-center justify-between group",
                              isSelected 
                                ? "bg-orange-500/10 border-orange-500/40" 
                                : "bg-black/40 border-white/5 hover:border-white/10 hover:bg-black/60"
                            )}
                          >
                            <div>
                              <span className="text-xs font-bold text-white block">{t.name}</span>
                              <span className="text-[9px] text-neutral-500 font-mono tracking-wide">{t.fontFamily}</span>
                            </div>
                            <div className="flex gap-1.5 shrink-0">
                              <span className="w-2.5 h-2.5 rounded-full border border-white/10" style={{ backgroundColor: t.colors.primary }} />
                              <span className="w-2.5 h-2.5 rounded-full border border-white/10" style={{ backgroundColor: t.colors.accent }} />
                              <span className="w-2.5 h-2.5 rounded-full border border-white/10" style={{ backgroundColor: t.colors.bg }} />
                            </div>
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  {/* Active Slide Layout Variants Section */}
                  <div className="space-y-2.5">
                    <span className="text-[9px] font-black uppercase tracking-[0.2em] text-neutral-500 block font-bold">Layout Visual Style</span>
                    {layoutsForType.length > 0 ? (
                      <div className="grid grid-cols-1 gap-2">
                        {layoutsForType.map((variant, index) => {
                          const isSelected = activeVariantIndex === index;
                          return (
                            <button
                              key={variant.id}
                              type="button"
                              onClick={() => changeSlideVariant(index)}
                              className={cn(
                                "w-full p-3 rounded-xl border text-left transition-all flex items-center justify-between group",
                                isSelected 
                                  ? "bg-orange-500/10 border-orange-500/40" 
                                  : "bg-black/40 border-white/5 hover:border-white/10 hover:bg-black/60"
                              )}
                            >
                              <span className="text-xs font-medium text-neutral-200 group-hover:text-white">{variant.name}</span>
                              <span className="text-[9px] font-mono text-neutral-500 uppercase">Style {index + 1}</span>
                            </button>
                          );
                        })}
                      </div>
                    ) : (
                      <p className="text-[10px] text-neutral-500 italic">No alternative styles for this layout type.</p>
                    )}
                  </div>

                  {/* Active Slide Background Selection Section */}
                  <div className="space-y-2.5">
                    <span className="text-[9px] font-black uppercase tracking-[0.2em] text-neutral-500 block font-bold">Slide Background Graphic</span>
                    <div className="grid grid-cols-3 gap-2">
                      {/* Gradient Default */}
                      <button
                        type="button"
                        onClick={() => changeSlideBackground(0)}
                        className={cn(
                          "aspect-video rounded-lg border flex flex-col items-center justify-center p-1 text-center transition-all bg-gradient-to-br from-neutral-900 to-black",
                          currentSlide.bgImageIndex === 0 || !currentSlide.bgImageIndex
                            ? "border-orange-500 shadow-sm"
                            : "border-white/5 hover:border-white/15"
                        )}
                      >
                        <span className="text-[8px] font-bold text-neutral-300">Default Gradient</span>
                      </button>
                      
                      {/* Background Images */}
                      {activeTheme.bgImages.map((img: string, idx: number) => {
                        const isSelected = currentSlide.bgImageIndex === idx + 1;
                        return (
                          <button
                            key={idx}
                            type="button"
                            onClick={() => changeSlideBackground(idx + 1)}
                            className={cn(
                              "aspect-video rounded-lg border overflow-hidden relative transition-all bg-black",
                              isSelected
                                ? "border-orange-500 shadow-sm"
                                : "border-white/5 hover:border-white/15"
                            )}
                          >
                            <img src={img} alt={`BG ${idx + 1}`} className="w-full h-full object-cover opacity-60 hover:opacity-85 transition-opacity" />
                            <span className="absolute bottom-1 right-1 bg-black/75 px-1 rounded text-[7px] font-mono text-neutral-400">#{idx + 1}</span>
                          </button>
                        );
                      })}
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </aside>

      </div>
    </div>
  );
}
