export interface NoteTheme {
  id: string;
  name: string;
  category: 'light' | 'professional' | 'colorful';
  bg: string;
  text: string;
  primary: string;
  accent: string;
  cardBg: string;
  border: string;
  link: string;
  btnText?: string;
  /** CSS font-family value applied to the note body */
  font: string;
  /** Google Fonts embed URL (use ?family=... format) */
  googleFont: string;
  desc?: string;
}

export const THEMES: NoteTheme[] = [
  // --- LIGHT THEMES ---
  {
    id: 'atmosphere',
    name: 'Atmosphere',
    category: 'light',
    bg: '#fafafa',
    text: '#18181b',
    primary: '#db2777',
    accent: '#7c3aed',
    cardBg: '#f4f4f5',
    border: '#e4e4e7',
    link: '#c084fc',
    btnText: '#ffffff',
    font: "'Inter', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap',
    desc: 'Clean pink and lavender glassmorphism light theme'
  },
  {
    id: 'snow',
    name: 'Snow',
    category: 'light',
    bg: '#ffffff',
    text: '#1f2937',
    primary: '#0ea5e9',
    accent: '#0284c7',
    cardBg: '#f3f4f6',
    border: '#e5e7eb',
    link: '#38bdf8',
    btnText: '#ffffff',
    font: "'DM Sans', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap',
    desc: 'Brilliant white background with clear sky blue highlights'
  },
  {
    id: 'cream',
    name: 'Cream',
    category: 'light',
    bg: '#fffdf9',
    text: '#27272a',
    primary: '#d97706',
    accent: '#f59e0b',
    cardBg: '#faf5e6',
    border: '#e9dfc6',
    link: '#ea580c',
    btnText: '#ffffff',
    font: "'Lora', serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&display=swap',
    desc: 'Soft ivory background with warm butterscotch details'
  },
  {
    id: 'cotton',
    name: 'Cotton',
    category: 'light',
    bg: '#f8fafc',
    text: '#334155',
    primary: '#f43f5e',
    accent: '#ec4899',
    cardBg: '#f1f5f9',
    border: '#e2e8f0',
    link: '#fb7185',
    btnText: '#ffffff',
    font: "'Nunito', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800&display=swap',
    desc: 'Cozy slate-white theme with soft cherry-red features'
  },
  {
    id: 'emerald-light',
    name: 'Emerald Light',
    category: 'light',
    bg: '#f0fdf4',
    text: '#14532d',
    primary: '#059669',
    accent: '#10b981',
    cardBg: '#dcfce7',
    border: '#bbf7d0',
    link: '#10b981',
    btnText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap',
    desc: 'Refreshing pastel green field guide style'
  },
  {
    id: 'lavender',
    name: 'Lavender',
    category: 'light',
    bg: '#faf5ff',
    text: '#3b0764',
    primary: '#7c3aed',
    accent: '#a78bfa',
    cardBg: '#f3e8ff',
    border: '#e9d5ff',
    link: '#9f7aea',
    btnText: '#ffffff',
    font: "'Quicksand', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap',
    desc: 'Gentle pale purple and violet watercolor aesthetic'
  },
  {
    id: 'peach',
    name: 'Peach',
    category: 'light',
    bg: '#fffaf0',
    text: '#7c2d12',
    primary: '#ea580c',
    accent: '#f97316',
    cardBg: '#ffedd5',
    border: '#fed7aa',
    link: '#f97316',
    btnText: '#ffffff',
    font: "'Poppins', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap',
    desc: 'Warm cream-orange tone with sweet apricot highlights'
  },
  {
    id: 'sakura',
    name: 'Sakura',
    category: 'light',
    bg: '#fff5f5',
    text: '#4a1d1d',
    primary: '#db2777',
    accent: '#f472b6',
    cardBg: '#ffe4e6',
    border: '#fecdd3',
    link: '#db2777',
    btnText: '#ffffff',
    font: "'Zen Maru Gothic', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@400;500;700&display=swap',
    desc: 'Japanese cherry blossom pink theme with crimson lettering'
  },
  {
    id: 'sky',
    name: 'Sky',
    category: 'light',
    bg: '#f0f9ff',
    text: '#0c4a6e',
    primary: '#0369a1',
    accent: '#38bdf8',
    cardBg: '#e0f2fe',
    border: '#bae6fd',
    link: '#0ea5e9',
    btnText: '#ffffff',
    font: "'Outfit', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800&display=swap',
    desc: 'Airy light blue horizon theme with clear sky tones'
  },
  {
    id: 'mint',
    name: 'Mint',
    category: 'light',
    bg: '#f0fdfb',
    text: '#134e4a',
    primary: '#0f766e',
    accent: '#2dd4bf',
    cardBg: '#ccfbf1',
    border: '#99f6e4',
    link: '#0d9488',
    btnText: '#ffffff',
    font: "'Figtree', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800&display=swap',
    desc: 'Crisp fresh mint and teal tones for an energetic clean feel'
  },

  // --- PROFESSIONAL THEMES ---
  {
    id: 'kraft',
    name: 'Kraft',
    category: 'professional',
    bg: '#f4efe4',
    text: '#2d241e',
    primary: '#8b5a2b',
    accent: '#cd853f',
    cardBg: '#eae3d2',
    border: '#d7cdb2',
    link: '#a0522d',
    btnText: '#ffffff',
    font: "'Crimson Pro', Georgia, serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@400;500;600;700&display=swap',
    desc: 'Vintage organic paper style with elegant brown serif typography'
  },
  {
    id: 'academic',
    name: 'Academic',
    category: 'professional',
    bg: '#ffffff',
    text: '#0f172a',
    primary: '#1e293b',
    accent: '#475569',
    cardBg: '#f8fafc',
    border: '#e2e8f0',
    link: '#3b82f6',
    btnText: '#ffffff',
    font: "'Source Serif 4', Georgia, serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@400;500;600;700&display=swap',
    desc: 'Clean, neutral-light layouts standard for research and thesis'
  },
  {
    id: 'sepia',
    name: 'Sepia',
    category: 'professional',
    bg: '#f4ecd8',
    text: '#433422',
    primary: '#5c4033',
    accent: '#8b5a2b',
    cardBg: '#eae0c8',
    border: '#d3c2a0',
    link: '#8b4513',
    btnText: '#ffffff',
    font: "'EB Garamond', Georgia, serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700&display=swap',
    desc: 'Warm reading-friendly antique paper tone with dark brown text'
  },
  {
    id: 'oxford',
    name: 'Oxford',
    category: 'professional',
    bg: '#f8fafc',
    text: '#0f172a',
    primary: '#0f172a',
    accent: '#334155',
    cardBg: '#f1f5f9',
    border: '#cbd5e1',
    link: '#1e3a8a',
    btnText: '#ffffff',
    font: "'Playfair Display', Georgia, serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800&display=swap',
    desc: 'Classic British library aesthetic with navy and heavy borders'
  },
  {
    id: 'executive',
    name: 'Executive',
    category: 'professional',
    bg: '#ffffff',
    text: '#1c1917',
    primary: '#44403c',
    accent: '#78716c',
    cardBg: '#f5f5f4',
    border: '#e7e5e4',
    link: '#292524',
    btnText: '#ffffff',
    font: "'IBM Plex Sans', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&display=swap',
    desc: 'High-contrast charcoal on warm white corporate layout'
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    category: 'professional',
    bg: '#fafafa',
    text: '#18181b',
    primary: '#09090b',
    accent: '#27272a',
    cardBg: '#f4f4f5',
    border: '#e4e4e7',
    link: '#09090b',
    btnText: '#ffffff',
    font: "'Space Grotesk', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap',
    desc: 'Ultra-clean layout stripped of all decorative colors'
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    category: 'professional',
    bg: '#f8fbff',
    text: '#1e3a5f',
    primary: '#1d4ed8',
    accent: '#3b82f6',
    cardBg: '#eff6ff',
    border: '#bfdbfe',
    link: '#2563eb',
    btnText: '#ffffff',
    font: "'Roboto Mono', monospace",
    googleFont: 'https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;600;700&display=swap',
    desc: 'Technical drafting-inspired blue-on-white engineering theme'
  },
  {
    id: 'linen',
    name: 'Linen',
    category: 'professional',
    bg: '#faf8f5',
    text: '#3d2b1f',
    primary: '#6b4c3b',
    accent: '#a07050',
    cardBg: '#f2ede7',
    border: '#e0d5c8',
    link: '#8b5e3c',
    btnText: '#ffffff',
    font: "'Merriweather', Georgia, serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap',
    desc: 'Natural off-white linen texture with earthy warm tones'
  },

  // --- COLORFUL THEMES ---
  {
    id: 'coral',
    name: 'Coral',
    category: 'colorful',
    bg: '#fff8f6',
    text: '#7f1d1d',
    primary: '#e11d48',
    accent: '#f97316',
    cardBg: '#ffe4e1',
    border: '#fecaca',
    link: '#e11d48',
    btnText: '#ffffff',
    font: "'Raleway', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700;800&display=swap',
    desc: 'Vibrant coral and warm orange tones on a light blush base'
  },
  {
    id: 'violet-mist',
    name: 'Violet Mist',
    category: 'colorful',
    bg: '#fdf4ff',
    text: '#4a044e',
    primary: '#9333ea',
    accent: '#c026d3',
    cardBg: '#fae8ff',
    border: '#f0abfc',
    link: '#a21caf',
    btnText: '#ffffff',
    font: "'Josefin Sans', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;500;600;700&display=swap',
    desc: 'Dreamy fuchsia and violet mist with soft purple highlights'
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    category: 'colorful',
    bg: '#fffbf0',
    text: '#78350f',
    primary: '#f59e0b',
    accent: '#f97316',
    cardBg: '#fef3c7',
    border: '#fde68a',
    link: '#d97706',
    btnText: '#ffffff',
    font: "'Cabin', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap',
    desc: 'Golden sunrise warmth with amber and orange glow on cream'
  },
  {
    id: 'breeze',
    name: 'Breeze',
    category: 'colorful',
    bg: '#f0f7ff',
    text: '#1e3a5f',
    primary: '#2563eb',
    accent: '#06b6d4',
    cardBg: '#dbeafe',
    border: '#bfdbfe',
    link: '#0284c7',
    btnText: '#ffffff',
    font: "'Karla', sans-serif",
    googleFont: 'https://fonts.googleapis.com/css2?family=Karla:wght@400;500;600;700;800&display=swap',
    desc: 'Fresh coastal breeze with cerulean blue and cyan highlights'
  },
];
