"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  IconArrowLeft,
  IconChartBar,
  IconDownload,
  IconPrinter,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconWorld,
  IconClock,
  IconTrendingUp,
  IconBrain,
  IconQuote,
  IconTimeline,
  IconSearch,
  IconArrowsDiff
} from "@tabler/icons-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";

// --- Mock Data ---
const MOCK_REPORT = {
  title: "Strategic Analysis: The Future of Generative AI",
  source: "YouTube: TechVision 2025 Keynote",
  duration: "42:15",
  generatedDate: "Oct 24, 2025",
  type: "Deep Analytics", // Default type for demo
  summary: "The video outlines a paradigm shift in software development, predicting that 60% of boilerplate code will be AI-generated by 2026. It highlights the transition from 'Copilots' to 'Agents' that can autonomously execute complex workflows. Key risks identified include data privacy in enterprise LLMs and the 'hallucination' barrier for critical systems.",
  
  // For Deep Analytics & Charts
  metrics: {
    sentiment: { current: 85, previous: 70 },
    complexity: { current: 72, previous: 65 },
    pacing: { current: 145, previous: 130 },
    clarity: { current: 92, previous: 88 }
  },
  topics: [
    { name: "Autonomous Agents", value: 45, prevValue: 30, color: "bg-emerald-500" },
    { name: "Enterprise Privacy", value: 30, prevValue: 40, color: "bg-blue-500" },
    { name: "LLM Infrastructure", value: 15, prevValue: 20, color: "bg-purple-500" },
    { name: "Ethics & Safety", value: 10, prevValue: 10, color: "bg-orange-500" }
  ],

  // For Timeline Analysis
  timeline: [
    { time: "05:20", title: "The Agentic Shift", description: "Introduction of autonomous agents replacing simple chat interfaces." },
    { time: "12:45", title: "Data Moats", description: "Discussion on why proprietary data is losing value compared to workflow integration." },
    { time: "24:30", title: "Hardware Constraints", description: "Analysis of GPU bottlenecks in edge computing devices." },
    { time: "38:15", title: "Future Outlook", description: "Predictions for 2026 market consolidation." }
  ],

  // For Web Search
  webSources: [
    { title: "Gartner 2025 AI Report", url: "gartner.com/ai-trends-2025", snippet: "Corroborates the 60% code generation prediction." },
    { title: "OpenAI Enterprise Privacy Docs", url: "openai.com/enterprise", snippet: "References data retention policies discussed in the video." },
    { title: "NVIDIA Edge Computing Specs", url: "nvidia.com/edge-ai", snippet: "Technical specs matching the hardware constraints mentioned." }
  ],

  keyInsights: [
    {
      title: "The 'Agentic' Shift",
      description: "Moving beyond chat interfaces to goal-oriented agents that can use tools and plan steps.",
      impact: "High Impact"
    },
    {
      title: "Data Moats are Dead",
      description: "Proprietary data is less valuable than proprietary workflows and context integration.",
      impact: "Medium Impact"
    },
    {
      title: "Compute Bottlenecks",
      description: "Hardware constraints may slow down the deployment of larger models in edge devices.",
      impact: "Critical Risk"
    }
  ],
  transcript_highlights: [
    "\"The cost of intelligence is dropping to zero, but the value of context is going to infinity.\"",
    "\"We are not building search engines anymore; we are building reasoning engines.\""
  ]
};

export default function ReportView() {
  const [activeTab, setActiveTab] = useState("overview"); // overview, analytics, timeline, sources
  const [compareMode, setCompareMode] = useState(false);

  return (
    <div className="min-h-screen bg-black text-white overflow-hidden flex flex-col relative font-sans selection:bg-emerald-500/30">
      
      {/* Background Ambience */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-[-10%] left-[20%] w-[600px] h-[600px] bg-emerald-900/10 rounded-full blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-blue-900/10 rounded-full blur-[120px]" />
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 brightness-100 contrast-150 mix-blend-overlay"></div>
      </div>

      {/* --- Header --- */}
      <header className="w-full max-w-6xl mx-auto p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 relative z-10 border-b border-white/5">
        <div className="flex items-center gap-4">
          <Button variant="ghost" className="rounded-full w-10 h-10 p-0 text-neutral-400 hover:text-white hover:bg-neutral-800">
            <IconArrowLeft className="w-5 h-5" />
          </Button>
          <div>
             <div className="flex items-center gap-2 mb-1">
                <IconChartBar className="w-5 h-5 text-emerald-400" />
                <span className="text-xs font-mono text-emerald-400 uppercase tracking-widest">Report</span>
                <Badge variant="outline" className="text-[10px] py-0 h-5 border-emerald-500/30 text-emerald-400 bg-emerald-500/10">
                  {MOCK_REPORT.type}
                </Badge>
             </div>
             <h1 className="text-xl sm:text-2xl font-bold text-white leading-tight">
              {MOCK_REPORT.title}
            </h1>
            <div className="flex items-center gap-3 text-xs text-neutral-500 mt-1">
              <span className="flex items-center gap-1"><IconClock className="w-3 h-3" /> {MOCK_REPORT.duration}</span>
              <span>•</span>
              <span>{MOCK_REPORT.source}</span>
              <span>•</span>
              <span>Generated {MOCK_REPORT.generatedDate}</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
           <Button variant="outline" className="border-neutral-800 bg-black/50 hover:bg-neutral-900 text-neutral-300 gap-2">
             <IconPrinter className="w-4 h-4" /> <span className="hidden sm:inline">Print</span>
           </Button>
           <Button className="bg-emerald-600 hover:bg-emerald-500 text-white gap-2 shadow-[0_0_15px_rgba(16,185,129,0.3)]">
             <IconDownload className="w-4 h-4" /> Export PDF
           </Button>
        </div>
      </header>

      {/* --- Main Dashboard --- */}
      <main className="flex-1 w-full max-w-6xl mx-auto p-4 sm:p-6 relative z-10 overflow-y-auto">
        
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <div className="flex justify-start mb-6 overflow-x-auto scrollbar-hide">
            <TabsList className="bg-neutral-900/50 border border-white/10 p-1 rounded-xl">
              <TabsTrigger value="overview" className="gap-2 data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
                <IconBrain className="w-4 h-4" /> Overview
              </TabsTrigger>
              <TabsTrigger value="analytics" className="gap-2 data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
                <IconTrendingUp className="w-4 h-4" /> Deep Analytics
              </TabsTrigger>
              <TabsTrigger value="timeline" className="gap-2 data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
                <IconTimeline className="w-4 h-4" /> Timeline
              </TabsTrigger>
              <TabsTrigger value="sources" className="gap-2 data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
                <IconSearch className="w-4 h-4" /> Web Sources
              </TabsTrigger>
            </TabsList>
          </div>

          {/* === OVERVIEW TAB === */}
          <TabsContent value="overview" className="mt-0 space-y-6 focus-visible:outline-none">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Executive Summary */}
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="lg:col-span-2 p-6 rounded-3xl bg-neutral-900/50 backdrop-blur-xl border border-white/10 relative overflow-hidden"
              >
                  <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500" />
                  <h2 className="text-lg font-semibold text-white mb-4">Executive Summary</h2>
                  <p className="text-neutral-300 leading-relaxed">
                    {MOCK_REPORT.summary}
                  </p>
                  
                  {/* Export Quick Links */}
                  <div className="mt-6 flex gap-3 pt-4 border-t border-white/5">
                    <button className="text-xs flex items-center gap-1.5 text-neutral-400 hover:text-white transition-colors">
                        <IconFileTypePdf className="w-4 h-4" /> PDF
                    </button>
                    <button className="text-xs flex items-center gap-1.5 text-neutral-400 hover:text-white transition-colors">
                        <IconFileTypeDoc className="w-4 h-4" /> DOCX
                    </button>
                    <button className="text-xs flex items-center gap-1.5 text-neutral-400 hover:text-white transition-colors">
                        <IconWorld className="w-4 h-4" /> Web Link
                    </button>
                  </div>
              </motion.div>

              {/* Quick Key Insights */}
              <div className="space-y-4">
                {MOCK_REPORT.keyInsights.map((insight, i) => (
                  <motion.div 
                    key={i}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="p-4 rounded-2xl bg-neutral-800/30 border border-white/5 hover:bg-neutral-800/50 transition-colors"
                  >
                      <div className="flex justify-between items-start mb-2">
                        <h4 className="font-semibold text-white text-sm">{insight.title}</h4>
                        <span className={cn(
                            "px-2 py-0.5 rounded text-[10px] font-medium uppercase border",
                            insight.impact === "High Impact" ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" :
                            insight.impact === "Critical Risk" ? "bg-red-500/10 text-red-400 border-red-500/20" :
                            "bg-blue-500/10 text-blue-400 border-blue-500/20"
                        )}>
                            {insight.impact}
                        </span>
                      </div>
                      <p className="text-xs text-neutral-400 line-clamp-2">{insight.description}</p>
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Quote Section */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="p-6 rounded-3xl bg-neutral-900/50 backdrop-blur-xl border border-white/10"
            >
              <h3 className="text-sm font-semibold text-neutral-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                  <IconQuote className="w-4 h-4" /> Key Moments
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {MOCK_REPORT.transcript_highlights.map((quote, i) => (
                    <div key={i} className="p-4 rounded-xl bg-black/40 border border-white/5 italic text-neutral-300 text-sm border-l-2 border-l-emerald-500">
                        {quote}
                    </div>
                  ))}
              </div>
            </motion.div>
          </TabsContent>

          {/* === ANALYTICS TAB === */}
          <TabsContent value="analytics" className="mt-0 space-y-6 focus-visible:outline-none">
             
             {/* Controls */}
             <div className="flex justify-end mb-4">
                <div className="flex items-center gap-2 bg-neutral-900 border border-white/10 p-1 rounded-lg">
                   <span className="text-xs text-neutral-400 px-2">Compare Mode</span>
                   <button 
                      onClick={() => setCompareMode(!compareMode)}
                      className={cn(
                        "w-8 h-5 rounded-full relative transition-colors duration-300",
                        compareMode ? "bg-emerald-600" : "bg-neutral-700"
                      )}
                   >
                      <div className={cn(
                        "absolute top-1 left-1 w-3 h-3 bg-white rounded-full transition-transform duration-300",
                        compareMode ? "translate-x-3" : "translate-x-0"
                      )} />
                   </button>
                </div>
             </div>

             <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                
                {/* Topic Distribution Chart */}
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="p-6 rounded-3xl bg-neutral-900/50 backdrop-blur-xl border border-white/10"
                >
                   <h3 className="text-sm font-semibold text-neutral-400 uppercase tracking-wider mb-6">Topic Distribution</h3>
                   
                   <div className="space-y-4">
                      {MOCK_REPORT.topics.map((topic, i) => (
                         <div key={i} className="space-y-1">
                            <div className="flex justify-between text-sm">
                               <span className="text-neutral-300">{topic.name}</span>
                               <span className="text-neutral-400">{topic.value}%</span>
                            </div>
                            <div className="h-2 w-full bg-neutral-800 rounded-full overflow-hidden relative">
                               {compareMode && (
                                  <div 
                                    style={{ width: `${topic.prevValue}%` }} 
                                    className="absolute top-0 left-0 h-full bg-white/20 w-full z-0" 
                                  />
                               )}
                               <motion.div 
                                  initial={{ width: 0 }}
                                  animate={{ width: `${topic.value}%` }}
                                  transition={{ duration: 1, delay: i * 0.1 }}
                                  className={cn("h-full relative z-10", topic.color)} 
                               />
                            </div>
                         </div>
                      ))}
                   </div>
                   {compareMode && (
                      <div className="mt-4 flex items-center gap-4 text-xs text-neutral-500 justify-end">
                         <div className="flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-white/20" /> Previous</div>
                         <div className="flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-emerald-500" /> Current</div>
                      </div>
                   )}
                </motion.div>

                {/* Content Metrics */}
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.1 }}
                  className="p-6 rounded-3xl bg-neutral-900/50 backdrop-blur-xl border border-white/10 flex flex-col justify-between"
                >
                   <div className="mb-4">
                      <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                         <IconTrendingUp className="w-5 h-5 text-emerald-400" /> Engagement Metrics
                      </h2>
                   </div>

                   <div className="space-y-6">
                      {Object.entries(MOCK_REPORT.metrics).map(([key, data], i) => (
                         <div key={key}>
                            <div className="flex justify-between text-xs mb-1 uppercase tracking-wider">
                               <span className="text-neutral-400">{key}</span>
                               <div className="flex gap-2">
                                  {compareMode && <span className="text-neutral-600 line-through">{data.previous}</span>}
                                  <span className={cn(
                                     "font-mono font-bold",
                                     compareMode && data.current > data.previous ? "text-emerald-400" : 
                                     compareMode && data.current < data.previous ? "text-red-400" : "text-white"
                                  )}>
                                     {data.current}
                                  </span>
                               </div>
                            </div>
                            <div className="flex items-end gap-1 h-2">
                               <div className="flex-1 h-full bg-neutral-800 rounded-full overflow-hidden relative">
                                  {compareMode && (
                                     <div 
                                        style={{ width: `${key === 'pacing' ? (data.previous/200)*100 : data.previous}%` }} 
                                        className="absolute top-0 left-0 h-full bg-white/10" 
                                     />
                                  )}
                                  <motion.div 
                                     initial={{ width: 0 }}
                                     animate={{ width: `${key === 'pacing' ? (data.current/200)*100 : data.current}%` }}
                                     transition={{ duration: 0.8, delay: i * 0.1 }}
                                     className={cn(
                                        "h-full", 
                                        key === 'sentiment' ? "bg-gradient-to-r from-emerald-600 to-emerald-400" :
                                        key === 'complexity' ? "bg-blue-500" :
                                        key === 'pacing' ? "bg-orange-500" : "bg-purple-500"
                                     )} 
                                  />
                               </div>
                            </div>
                         </div>
                      ))}
                   </div>
                </motion.div>
             </div>
          </TabsContent>

          {/* === TIMELINE TAB === */}
          <TabsContent value="timeline" className="mt-0 focus-visible:outline-none">
             <div className="p-6 rounded-3xl bg-neutral-900/50 backdrop-blur-xl border border-white/10">
                <div className="relative border-l-2 border-emerald-500/30 ml-4 space-y-8 py-4">
                   {MOCK_REPORT.timeline.map((event, i) => (
                      <motion.div 
                        key={i}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="relative pl-8"
                      >
                         <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-black border-2 border-emerald-500 z-10" />
                         <span className="text-xs font-mono text-emerald-400 mb-1 block">{event.time}</span>
                         <h4 className="text-white font-semibold text-lg">{event.title}</h4>
                         <p className="text-neutral-400 text-sm mt-1 max-w-2xl">{event.description}</p>
                      </motion.div>
                   ))}
                </div>
             </div>
          </TabsContent>

          {/* === SOURCES TAB === */}
          <TabsContent value="sources" className="mt-0 focus-visible:outline-none">
             <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {MOCK_REPORT.webSources.map((source, i) => (
                   <motion.div 
                      key={i}
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      transition={{ delay: i * 0.1 }}
                      className="p-5 rounded-2xl bg-neutral-900/50 border border-white/10 hover:border-emerald-500/50 hover:bg-neutral-900/80 transition-all cursor-pointer group"
                   >
                      <div className="flex items-center gap-2 mb-3">
                         <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 group-hover:bg-emerald-500/20 transition-colors">
                            <IconWorld className="w-5 h-5" />
                         </div>
                         <span className="text-xs text-neutral-500 truncate max-w-[150px]">{source.url}</span>
                      </div>
                      <h4 className="text-white font-medium mb-2 group-hover:text-emerald-300 transition-colors">{source.title}</h4>
                      <p className="text-xs text-neutral-400 leading-relaxed">{source.snippet}</p>
                   </motion.div>
                ))}
             </div>
          </TabsContent>

        </Tabs>

      </main>

    </div>
  );
}