import AIMetadataRemoverClient from "@/components/tools/AIMetadataRemoverClient";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "LinkedIn C Tag Remover – Hide Cr Tag from AI Images on LinkedIn | Paperxify",
  description: "Need to hide the AI Cr tag on LinkedIn posts? Use our free LinkedIn C tag remover to strip C2PA authenticity credentials, AI info, and prompts from images instantly. Keep camera EXIF intact or strip all metadata.",
  keywords: [
    "linkedin c tag remover",
    "hide cr tag from ai images on linkedin",
    "ai info from img removal",
    "remove linkedin ai tag",
    "hide ai label linkedin",
    "strip c2pa from images",
    "remove content credentials",
    "ai metadata remover",
    "linkedin ai label bypass",
    "midjourney c2pa remover"
  ],
  alternates: {
    canonical: "https://paperxify.com/tools/ai-metadata-remover",
  },
  openGraph: {
    title: "LinkedIn C Tag Remover – Hide Cr Tag from AI Images on LinkedIn | Paperxify",
    description: "Need to hide the AI Cr tag on LinkedIn posts? Use our free LinkedIn C tag remover to strip C2PA authenticity credentials, AI info, and prompts from images instantly.",
    type: "website",
    url: "https://paperxify.com/tools/ai-metadata-remover",
    siteName: "Paperxify",
  },
  twitter: {
    card: "summary_large_image",
    title: "LinkedIn C Tag Remover & AI Metadata Scrubber",
    description: "Hide the AI Cr tag on LinkedIn posts. Strip C2PA credentials, prompts, and AI metadata client-side.",
  }
};

export default function Page() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": "LinkedIn C Tag Remover & AI Metadata Scrubber - Paperxify",
    "url": "https://paperxify.com/tools/ai-metadata-remover",
    "description": "Hide the AI Cr tag on LinkedIn posts. Strip C2PA authenticity credentials, prompts, and AI metadata client-side while keeping EXIF intact.",
    "applicationCategory": "UtilityApplication",
    "operatingSystem": "All",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    }
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "How to hide the Cr tag from AI images on LinkedIn?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To hide the Cr tag, upload your AI-generated image (from Midjourney, ChatGPT, DALL-E, or Stable Diffusion) to this page, choose 'Remove Only AI Metadata (Recommended)', and download the cleaned version. LinkedIn will no longer display the AI tag because the C2PA Content Credentials have been stripped from the file headers."
        }
      },
      {
        "@type": "Question",
        "name": "What is a LinkedIn C tag and how does it work?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The C tag (Content Credentials label) is a small tag added by LinkedIn when it detects C2PA/JUMBF metadata headers in uploaded files. These headers are automatically appended by AI tools like Midjourney or DALL-E to disclose that the image was generated by AI. Removing this metadata strips the tag."
        }
      },
      {
        "@type": "Question",
        "name": "How do I perform AI info from img removal client-side?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Our free LinkedIn C Tag Remover parses the raw bytes of PNG, JPEG, and WebP images directly in your browser. It identifies and removes C2PA digital signatures, comments, prompts, and seed information, and gives you a download link without sending your file to any server."
        }
      }
    ]
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <AIMetadataRemoverClient />
    </>
  );
}
