"use client";

import React, { useState, useEffect } from "react";
import { 
  Users, FileText, UploadCloud, CheckCircle2, 
  PlayCircle, Eye, RefreshCcw, Crown 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import api from "@/config/api";
import { cn } from "@/lib/utils";

// --- LIVE A4 PDF PREVIEW COMPONENT ---
const PDFPreview = ({ data }: { data: any }) => {
  return (
    <div className="w-full bg-neutral-900/50 p-4 rounded-xl border border-white/10 flex flex-col items-center gap-4 h-full">
      <div className="flex items-center justify-between w-full px-4">
        <div className="flex items-center gap-2 text-xs font-bold text-neutral-400 uppercase tracking-widest">
          <Eye size={12} /> Live PDF Preview
        </div>
        <Badge variant={data.type === 'premium' ? "default" : "secondary"} className="uppercase text-[10px]">
          {data.type} Note
        </Badge>
      </div>

      {/* A4 Paper Container - Scaled to fit */}
      <div className="flex-1 w-full overflow-hidden flex justify-center bg-neutral-950/30 rounded-lg border border-white/5 relative">
        <div className="absolute inset-0 overflow-y-auto custom-scrollbar p-8 flex justify-center">
            
            {/* The Paper */}
            <div className="bg-white text-black w-[210mm] min-h-[297mm] shadow-2xl p-[20mm] origin-top transform scale-[0.5] md:scale-[0.6] lg:scale-[0.7]">
              
              {/* Header */}
              <div className="border-b-2 border-red-600 pb-4 mb-6">
                <h1 className="text-3xl font-bold text-neutral-900 leading-tight">
                  {data.title || "Note Title Goes Here..."}
                </h1>
                <div className="flex gap-4 mt-2 text-gray-500 text-sm">
                  <span>Level: <strong>{data.detailLevel}</strong></span>
                  <span>•</span>
                  <span>Generated: {new Date().toLocaleDateString()}</span>
                </div>
              </div>

              {/* Content Body */}
              <div 
                className="prose max-w-none text-sm leading-relaxed text-gray-800"
                dangerouslySetInnerHTML={{ 
                  __html: data.content || "<p>Start typing your note content...</p><ul><li>Points will appear here</li></ul>" 
                }}
              />

              {/* Footer */}
              <div className="mt-16 pt-6 border-t border-gray-200 flex justify-between text-xs text-gray-400 font-sans">
                <span>Generated by AI Note Engine</span>
                <span>Page 1 of 1</span>
              </div>

            </div>

        </div>
      </div>
    </div>
  );
};

export default function FakerDashboard() {
  // User State
  const [fakeUsers, setFakeUsers] = useState<any[]>([]);
  const [selectedUser, setSelectedUser] = useState<string>("");
  const [genCount, setGenCount] = useState(5);
  const [loading, setLoading] = useState(false);

  // Form Data State
  const [formData, setFormData] = useState({
    videoUrl: "",
    title: "",
    type: "free", // free or premium
    detailLevel: "Standard", // Short, Standard, Comprehensive
    content: "<h2>Introduction</h2><p>Summary of the video content goes here...</p><h3>Key Takeaways</h3><ul><li>Point 1</li><li>Point 2</li></ul>"
  });

  // --- FETCH USERS ---
  const fetchFakeUsers = async () => {
    try {
      const res = await api.get("/admin/faker/users");
      if (res.data.success) {
        setFakeUsers(res.data.data);
        if (res.data.data.length > 0 && !selectedUser) setSelectedUser(res.data.data[0]._id);
      }
    } catch (e) { console.error("Error"); }
  };
  useEffect(() => { fetchFakeUsers(); }, []);

  // --- GENERATE USERS ---
  const handleGenerateUsers = async () => {
    setLoading(true);
    try {
      await api.post("/admin/faker/users/create", { count: genCount });
      toast.success("Users Created");
      fetchFakeUsers();
    } catch (e) { toast.error("Failed"); } 
    finally { setLoading(false); }
  };

  // --- INJECT NOTE ---
  const handleInjectNote = async () => {
    if (!selectedUser) return toast.error("Select a User");
    if (!formData.videoUrl) return toast.error("Enter YouTube URL");

    setLoading(true);
    try {
      await api.post("/admin/faker/inject", {
        userId: selectedUser,
        type: "note",
        data: formData // Sending structured form data
      });
      toast.success("Note Injected Successfully!");
      setFormData({ ...formData, title: "", videoUrl: "" }); // Reset partial
    } catch (e) {
      toast.error("Injection Failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#050505] text-white p-4 md:p-8 font-sans pb-32">
      <header className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-black uppercase italic tracking-tighter text-white">
            Faker <span className="text-red-600">Studio</span>
          </h1>
          <p className="text-xs font-bold text-neutral-500 uppercase tracking-widest mt-1">
            Manual Content Injection System
          </p>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-[calc(100vh-150px)]">
        
        {/* --- LEFT: USER LIST (2 Cols) --- */}
        <div className="lg:col-span-3 flex flex-col gap-4 bg-[#0a0a0a] border border-white/10 rounded-2xl p-4 overflow-hidden">
          <div className="flex justify-between items-center">
            <h3 className="text-xs font-bold text-neutral-400 uppercase">Target User</h3>
            <div className="flex gap-2">
              <Input type="number" value={genCount} onChange={e=>setGenCount(parseInt(e.target.value))} className="w-12 h-7 text-xs bg-[#111] border-white/10" />
              <Button size="sm" onClick={handleGenerateUsers} disabled={loading} className="h-7 text-[10px] bg-white text-black hover:bg-gray-200">New</Button>
            </div>
          </div>
          
          <div className="flex-1 overflow-y-auto custom-scrollbar space-y-2">
            {fakeUsers.map(user => (
              <div key={user._id} onClick={() => setSelectedUser(user._id)}
                className={cn("p-2 rounded-lg border flex items-center justify-between cursor-pointer transition-all", selectedUser === user._id ? "bg-red-900/20 border-red-600/50" : "bg-[#151515] border-transparent hover:bg-white/5")}>
                <div className="flex items-center gap-2 overflow-hidden">
                  <Avatar className="h-6 w-6 border border-white/10"><AvatarImage src={user.picture} /></Avatar>
                  <div className="min-w-0">
                    <p className="text-[11px] font-bold text-neutral-200 truncate">{user.name}</p>
                    <p className="text-[9px] text-neutral-500 truncate">{user.email}</p>
                  </div>
                </div>
                {user.membership?.isActive && <Crown size={10} className="text-yellow-500" />}
              </div>
            ))}
          </div>
        </div>

        {/* --- MIDDLE: INPUT FORM (4 Cols) --- */}
        <div className="lg:col-span-4 flex flex-col gap-5 bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 overflow-y-auto custom-scrollbar">
          
          <div className="space-y-4">
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-neutral-500 uppercase">YouTube Link</label>
              <div className="relative">
                <PlayCircle className="absolute left-3 top-2.5 text-neutral-500" size={16} />
                <Input 
                  value={formData.videoUrl} 
                  onChange={(e) => setFormData({...formData, videoUrl: e.target.value})} 
                  placeholder="https://youtube.com/watch?v=..." 
                  className="bg-[#111] border-white/10 pl-10" 
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-bold text-neutral-500 uppercase">Note Title</label>
              <Input 
                value={formData.title} 
                onChange={(e) => setFormData({...formData, title: e.target.value})} 
                placeholder="Enter complete title..." 
                className="bg-[#111] border-white/10 font-bold" 
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-neutral-500 uppercase">Access Type</label>
                <Select value={formData.type} onValueChange={(v) => setFormData({...formData, type: v})}>
                  <SelectTrigger className="bg-[#111] border-white/10"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="free">Free</SelectItem>
                    <SelectItem value="premium">Premium</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-neutral-500 uppercase">Detail Level</label>
                <Select value={formData.detailLevel} onValueChange={(v) => setFormData({...formData, detailLevel: v})}>
                  <SelectTrigger className="bg-[#111] border-white/10"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Short">Short</SelectItem>
                    <SelectItem value="Standard">Standard</SelectItem>
                    <SelectItem value="Comprehensive">Comprehensive</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2 flex-1 flex flex-col">
              <label className="text-[10px] font-bold text-neutral-500 uppercase">Note Content (HTML)</label>
              <Textarea 
                value={formData.content} 
                onChange={(e) => setFormData({...formData, content: e.target.value})} 
                className="bg-[#111] border-white/10 font-mono text-xs text-neutral-300 min-h-[300px] resize-none focus-visible:ring-1 focus-visible:ring-red-600"
                placeholder="<h1>Topic</h1><p>Content...</p>"
              />
            </div>
          </div>

          <Button 
            onClick={handleInjectNote} 
            disabled={loading || !selectedUser} 
            className="w-full bg-green-600 hover:bg-green-700 text-white font-black uppercase tracking-widest h-12 rounded-xl mt-auto"
          >
            {loading ? "Processing..." : "Generate & Inject Note"}
          </Button>

        </div>

        {/* --- RIGHT: LIVE PREVIEW (5 Cols) --- */}
        <div className="lg:col-span-5 h-full overflow-hidden">
          <PDFPreview data={formData} />
        </div>

      </div>
    </div>
  );
}